# Generated by Django 2.2.17 on 2020-12-14 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20201209_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(default='invited', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('user', 'team')},
        ),
    ]
