# Generated by Django 2.2.5 on 2019-09-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_challenge_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='version',
            field=models.CharField(default='2019_01', max_length=31),
            preserve_default=False,
        ),
    ]
