# Generated by Django 2.2.5 on 2019-09-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_auto_20190905_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='script',
            field=models.CharField(choices=[('default', 'updater/Challenge.groovy'), ('parallel', 'updater/ChallengeUniprot.groovy')], default='updater/Challenge.groovy', max_length=31),
        ),
    ]
