# Generated by Django 2.2.17 on 2021-01-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_auto_20190906_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='hits_10',
            field=models.FloatField(null=True),
        ),
    ]
