# Generated by Django 2.2.17 on 2021-01-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_auto_20210120_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='auc',
            field=models.FloatField(null=True),
        ),
    ]
