# Generated by Django 2.2.17 on 2021-01-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_auto_20210120_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='download_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
