# Generated by Django 2.2.17 on 2021-01-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_submission_auc'),
        ('challenge', '0010_challenge_download_link'),
    ]

    operations = [
    ]
